name: Addictzone-Chests
version: '${project.version}'
main: de.ruben.addictzonechests.AddictzoneChests
api-version: 1.16
depend: [ XCore ]
authors: [ Ruben ]
description: The Lootchest Plugin from Addictzone
